#!/bin/bash

echo -e "Check kernel version:\n"
cat /proc/version && uname -a
echo -e "\n"
echo -e "Check x86_64 support:\n"
/lib64/ld-linux-x86-64.so.2 --help | grep "(supported, searched)"
echo -e "\n"
echo -e "Check CPU config:\n"
zgrep -i CONFIG_GENERIC_CPU /proc/config.gz | grep -wE '\w{18,19}'
echo -e "\n"
echo -e "Current disk schedulers:\n"
for disk in /sys/block/*/; do
    if [[ -f $disk/queue/scheduler ]]; then
        echo "`basename "$disk"`: `cat $disk/queue/scheduler`"
    fi
done
echo -e "\nCheck available schedulers:\n"
journalctl -k | grep -i scheduler